model:
  type: dsq_mixnet_m
dataset: cifar100
cutout: 16
batch: 1024
epoch: 50
lr: 0.001
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 1.01
    epoch: 10
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
